version: '3'
services:
  splash:
    image: "scrapinghub/splash:latest"
    ports:
      - "8050:8050"

  misbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: misbot.v4.1
    ports:
     - "8443:8443"
    links:
      - "splash:splash"
    depends_on:
      - splash
    volumes:
      - ./mis_bot/:/app
